def load_test_data
  @chef1 = Chef.create({name: "Peter"})
  @chef2 = Chef.create({name: "Clark"})
  @chef3 = Chef.create({name: "Jacob"})

  @dish1 = @chef1.dishes.create({name: "Mac-n-Cheese", description: "Elbow pasta served in a creamy cheese sauce"})
  @dish2 = @chef1.dishes.create({name: "Fried Chicken", description: "Crispy chicken fried to perfection!"})
  @dish3 = @chef1.dishes.create({name: "French Dip", description: "Classic roast beef sandwich served with broth"})
  @dish4 = @chef2.dishes.create({name: "Pancakes", description: "fluffy stack of pancakes served with butter+syrup"})
  @dish5 = @chef2.dishes.create({name: "Crepes", description: "thin delicate french style pancakes"})
  @dish6 = @chef2.dishes.create({name: "Scrambled Eggs", description: "Fluffy scrambled eggs cooked with cheddar cheese and milk"})
  @dish7 = @chef3.dishes.create({name: "Steak and Potatoes", description: "8 oz steak and potatoes, cooked to order"})
  @dish8 = @chef3.dishes.create({name: "Fried Fish", description: "Lightly breaded fish pan fried and garnished with lemon"})
  @dish9 = @chef3.dishes.create({name: "Lasagna", description: "Just like Mom used to make!"})

  @ingredient1 = Ingredient.create({name: "Pasta", calories: 400})
  @ingredient2 = Ingredient.create({name: "Chicken", calories: 350})
  @ingredient3 = Ingredient.create({name: "Beef", calories: 440})
  @ingredient4 = Ingredient.create({name: "Flour", calories: 30})
  @ingredient5 = Ingredient.create({name: "Cheese", calories: 375})
  @ingredient6 = Ingredient.create({name: "Eggs", calories: 120})
  @ingredient7 = Ingredient.create({name: "Fish", calories: 150})
  @ingredient8 = Ingredient.create({name: "Potatoes", calories: 200})
  @ingredient9 = Ingredient.create({name: "Milk", calories: 80})

  DishIngredient.create({dish_id: @dish1.id, ingredient_id: @ingredient1.id})
  DishIngredient.create({dish_id: @dish1.id, ingredient_id: @ingredient5.id})
  DishIngredient.create({dish_id: @dish2.id, ingredient_id: @ingredient2.id})
  DishIngredient.create({dish_id: @dish2.id, ingredient_id: @ingredient4.id})
  DishIngredient.create({dish_id: @dish3.id, ingredient_id: @ingredient3.id})
  DishIngredient.create({dish_id: @dish3.id, ingredient_id: @ingredient5.id})
  DishIngredient.create({dish_id: @dish4.id, ingredient_id: @ingredient4.id})
  DishIngredient.create({dish_id: @dish4.id, ingredient_id: @ingredient9.id})
  DishIngredient.create({dish_id: @dish5.id, ingredient_id: @ingredient4.id})
  DishIngredient.create({dish_id: @dish5.id, ingredient_id: @ingredient9.id})
  DishIngredient.create({dish_id: @dish6.id, ingredient_id: @ingredient6.id})
  DishIngredient.create({dish_id: @dish6.id, ingredient_id: @ingredient5.id})
  DishIngredient.create({dish_id: @dish6.id, ingredient_id: @ingredient9.id})
  DishIngredient.create({dish_id: @dish7.id, ingredient_id: @ingredient3.id})
  DishIngredient.create({dish_id: @dish7.id, ingredient_id: @ingredient8.id})
  DishIngredient.create({dish_id: @dish8.id, ingredient_id: @ingredient7.id})
  DishIngredient.create({dish_id: @dish8.id, ingredient_id: @ingredient4.id})
  DishIngredient.create({dish_id: @dish9.id, ingredient_id: @ingredient1.id})
  DishIngredient.create({dish_id: @dish9.id, ingredient_id: @ingredient3.id})
  DishIngredient.create({dish_id: @dish9.id, ingredient_id: @ingredient5.id})
end